// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseAndOpenArchive():Promise<Array<string>>;

export function CloseArchive():Promise<void>;

export function GetPageDataURL(arg1:number):Promise<string>;

export function ListPages():Promise<Array<string>>;

export function OpenArchive(arg1:string):Promise<void>;
