// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseAndOpenArchive() {
  return window['go']['main']['App']['ChooseAndOpenArchive']();
}

export function CloseArchive() {
  return window['go']['main']['App']['CloseArchive']();
}

export function GetPageDataURL(arg1) {
  return window['go']['main']['App']['GetPageDataURL'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListPages() {
  return window['go']['main']['App']['ListPages']();
}

export function OpenArchive(arg1) {
  return window['go']['main']['App']['OpenArchive'](arg1);
}
